server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/weather/weather {
        proxy_pass http://weather-service:3001/weather;
        proxy_set_header Host $host;
    }

    location /api/weather/forecast {
        proxy_pass http://weather-service:3001/forecast;
        proxy_set_header Host $host;
    }

    location /api/recommend/recommend {
        proxy_pass http://recommendation-service:3002/recommend;
        proxy_set_header Host $host;
    }
}